environment:
  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    QTPATH: C:\Qt\5.13\msvc2017_64
    OS: win64
    VCVARSALLPATH: C:\"Program Files (x86)\Microsoft Visual Studio"\2019\Community\VC\Auxiliary\Build\vcvarsall.bat
    VCVARSALL: x64
  - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
    OS: linux
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    QTPATH: C:\Qt\5.13\msvc2017
    OS: win32
    VCVARSALLPATH: C:\"Program Files (x86)\Microsoft Visual Studio"\2019\Community\VC\Auxiliary\Build\vcvarsall.bat
    VCVARSALL: x86

install:
    - git submodule update --init --recursive    
    
before_build:
    # Windows
    - cmd: set PATH=%QTPATH%\bin;C:\Qt\Tools\QtCreator\bin;%PATH%
    - cmd: call %VCVARSALLPATH% %VCVARSALL%
    # Linux
    - sh: sudo apt-get -qq update
    - sh: sudo apt-get install -y build-essential qtbase5-dev qt5-qmake qt5-default
    
build_script:
    - qmake RaidFinder.pro
    # Windows
    - cmd: jom -j %NUMBER_OF_PROCESSORS%
    # Linux
    - sh: make -j $(nproc)
    
after_build:
    # Windows
    - cmd: md RaidFinder-windows
    - cmd: move release\RaidFinder.exe RaidFinder-windows\RaidFinder.exe 
    - cmd: move raid_solver.py RaidFinder-windows\raid_solver.py
    - cmd: windeployqt --release --no-translations --no-angle --no-plugins --no-opengl-sw RaidFinder-windows\RaidFinder.exe
    - cmd: del RaidFinder-windows\vc_redist*.exe
    - cmd: xcopy /I %QTPATH%\plugins\platforms\qwindows.dll RaidFinder-windows\platforms\
    - cmd: xcopy /I %QTPATH%\plugins\styles\qwindowsvistastyle.dll RaidFinder-windows\styles\
    - cmd: 7z a RaidFinder-%OS%.zip RaidFinder-windows\
    - cmd: sha256sum RaidFinder-%OS%.zip > RaidFinder-%OS%.zip.sha256
    # Linux
    - sh: zip RaidFinder-linux.zip RaidFinder raid_solver.py
    - sh: sha256sum RaidFinder-linux.zip > RaidFinder-linux.zip.sha256
    
artifacts:
- path: RaidFinder-%OS%.zip
- path: RaidFinder-%OS%.zip.sha256

deploy:
    provider: GitHub
    description: ''
    auth_token:
        secure: u3c5wUq11csZ77TpgKMImu9U+ibNiviMcEpTuQXmqp1YGSHA/+u5FhqZ3KRZBAQX
    artifact: RaidFinder-%OS%.zip,RaidFinder-%OS%.zip.sha256
    on:
        APPVEYOR_REPO_TAG: true
